name: Flatpak build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
      options: --privileged

    steps:
    - name: Checkout flatpak build templates
      uses: actions/checkout@v4
      with:
        repository: project-imprimis/org.imprimis.Imprimis.flatpak
        submodules: true

    - name: Build flatpak
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: imprimis.flatpak
        manifest-path: org.imprimis.Imprimis.json
        cache-key: flatpak-builder-${{ github.sha }}

    - name: Debug information
      run: ls *
